Initial test-fixing work
slavapestov/swift pull request #1
Opened 2017-04-02 03:19 UTC by brentdax

These commits fix all broken `-t` tests on macOS; I'll be checking `-T` next, but I figure this is a good starting point.

(No idea if submitting a PR to your branch is the best way to get this stuff into your apple/swift PR, but I thought it was worth a try. If there's a better way to do it, let me know.)

2017-04-06 00:48 UTC, slavapestov commented
Oh I didn't see this until now, sorry. Do you want to create a new PR and add my patch to it against Apple/swift instead? I'd want @rudkx to look at the changes too.

2017-04-06 06:41 UTC, rudkx requested changes

2017-04-06 06:41 UTC, rudkx commented on lib/Sema/CSGen.cpp
> +      }
I've been working on moving the constraint system over to use a side map for types, which are accessed via ConstraintSystem::getType(Expr *) and set via ConstraintSystem::setType(Expr *, Type), so those should be used here (at the moment they still set the type directly on the expression, but that will be going away).

2017-04-07 09:03 UTC, brentdax commented on lib/Sema/CSGen.cpp
> +      }
Right, I've actually used that a couple times—sorry! Would the correct line be this?

    CS.setType(E, E->getDecl()->getInterfaceType());

You mention `ConstraintSystem::getType()`, but I don't think that works on `Decl`s.

2017-04-07 09:04 UTC, brentdax commented
@slavapestov Once I've heard from @rudkx, I'll make a PR against apple/swift. Thanks for your help on this!

2017-04-07 23:54 UTC, rudkx commented on lib/Sema/CSGen.cpp
> +      }
Yes, I just mentioned that for completeness regarding setting/getting types on Exprs. Your CS.setType call looks correct!

2017-04-08 10:18 UTC, closed without merging